MINT_ENABLED_MODIFY_MODE = False
MINT_ENABLED_REPLAY_MODE = False
MINT_ENABLED_GENERATED_MODE = False

MINT_ENABLED_CHECK_SESSION = False

MINT_PCAP_INPUT_FILES_PATH = []
MINT_PCAP_OUTPUT_FILES_PATH = []

MINT_SMAC_REPLACE_LIST = {}
MINT_DMAC_REPLACE_LIST = {}

MINT_SIP_REPLACE_LIST = {}
MINT_DIP_REPLACE_LIST = {}

MINT_SPECIFIED_INTERFACE = None
MINT_SAVE_TO_PCAPNG_FILE = False

MINT_PARAM_OPT = None
MINT_PARAM_DESC = None
MINT_PARAM_FUNC = None